server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    vault:
      enabled: true
      token: hvs.vt47wTVAvmHTyurHgstV9ms1
      host: localhost
      port: 8200
      scheme: http

management:
  endpoints:
    web:
      exposure:
        include: "*"
